# Generated by Django 3.1.4 on 2021-07-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvote',
            new_name='vate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvote',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.post'),
        ),
    ]
