# Generated by Django 3.1.4 on 2021-07-10 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20210710_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vate',
        ),
        migrations.AddField(
            model_name='post',
            name='vote_post',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
